### ISSUE TITLE
Act not quitting properly on Ubuntu 14.04 LTS ('Device can't keep up' message not logged, zombie process)

### ISSUE THREAD

**Issue by ArwedSchmidt** [aerospike/act#23]
We ran a few benchmarking rounds by now. On our initial setup we used Ubuntu 14.04 (LTS) and now that we switched to CentOS we noticed that Act under CentOS fails properly / user friendly while Act under Ubuntu would leave only question marks behind.

We noticed that at some point the act process would simply stop dumping into the output file (checked with tail) while the process kept running as normal (using same cpu resources as before!) without any hint what happened. The output didn't contain a device can't keep up message (tried to grep). Process couldn't be killed with SIGTERM or SIGKILL (as root), hinting at some kind of an "waiting for I/O"-deadlock. Out of 4-5x this happened, it only exited smoothly 1x. With CentOS we haven't experience any unsmooth exit so far.

It was only strace that would bring down the process and hint at an output into stdout with the message "device can't keep up". Unfortunately we didn't save the strace output. Can anybody confirm that this is a general issue? Is it supposed/unavoidable to die like this? If not, we are ready to reinstall ubuntu and re-produce the situation, if further input is necessary. 

On both OS we started act with an &-operator.

**Comment by wchu-citrusleaf** [comment]
Looking into dmesg may alos provide additional input, such as process OOM or other system failures.

**Comment by bayoukingpin** [comment]
I am guessing here that you are testing on an NVMe device. One thing to take note of is the kernel level. This directly impacts the default NVMe driver version. I recommend using Linux kernel 3.15 or higher and/or upgrading to the latest stable NVMe driver. We have seen this problem before. It was particularly bad on CentOS 6.x 2.6.x kernel. Basically, the NVMe driver was not stable with the older kernel.

Also, older Linux kernel versions can lead to weird numbers on standard tools like iostat, so this is not an Aerospike ACT specific thing.

**Comment by ArwedSchmidt** [comment]
Thanks for your reply. We'll try to reproduce this issue in the next weeks and provide further input (especially strace) if useful for the project. We have normal SATA drives (AHCI) but can't rule out for now that it's somewhat related to the combination of these drives with our mainboard and ubuntu/debian. 
The biggest concern for us was that it failed so silently and actually seemed to carry on with benchmarking (without dumping histograms). But it's not a show stopper..

**Comment by bayoukingpin** [comment]
Please let us know if we can help. This is quite unusual, but we have seen this before. If this is SATA, the other question is how the SSDs are connected to the motherboard. If it is plugging in directly, then this is the first time I have seen this. I do a lot of testing for Aerospike, so this would be very rare then. However, if you are going through a RAID controller, it may be related to that. It would then depend very heavily on the exact controller and the configuration. Unfortunately most of the tuning guides for those point to maximizing bandwidth rather than high random IOPS, so may lead to improper configuration. We can take this offline if you wish. I have a lot of experience both testing drives and interpreting why performance might be sub-optimal.

**Comment by ArwedSchmidt** [comment]
Closing this. I have no hardware available for another test setup. No such issues under CentOS on the same system, btw.

Cheers,
Arwed
