### ISSUE TITLE
act_prep take 10x longer in 5.0

### ISSUE THREAD

**Issue by yuyantingzero** [aerospike/act#39]
Hi,
I started using act 5.0 recently and noticed act 5.0 salting (14MB/sec) take much longer compared to 4.0 (400MB/sec).
After a bit digging, difference seems like caused by O_DSYNC flag. I am wondering will this invalidate my test results if I patch out O_DSYNC flag during salting.
Thanks!

**Comment by gooding470** [comment]
Thanks for pointing that out.  We will investigate.  Meanwhile, I doubt O_DSYNC would make any difference to the eventual result, if you only change it for salting.

In most situations we had not noticed any difference caused by that flag during actual testing (as opposed to salting) with ACT, or with Aerospike's server, so if you notice a difference there please tell us.

**Comment by yuyantingzero** [comment]
Thanks for the quick reply. Will let you know if seeing anything interesting.
